services:
  bot:
    container_name: telegram-feedback-bot
    image: ghcr.io/z0xca/telegram-feedback-bot:latest
    stop_signal: SIGINT
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone
      - ./config.yaml:/app/config.yaml
    command: python3 -m src
